# Generated by Django 4.1.7 on 2023-03-03 12:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("mall", "0004_order_orderedproduct_order_product_set_order_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict, editable=False, verbose_name="포트원 결제내역"
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="쇼핑몰 결제식별자"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="결제명")),
                (
                    "desired_amount",
                    models.PositiveIntegerField(editable=False, verbose_name="결제금액"),
                ),
                (
                    "buyer_name",
                    models.CharField(
                        editable=False, max_length=100, verbose_name="구매자 이름"
                    ),
                ),
                (
                    "buyer_email",
                    models.EmailField(
                        editable=False, max_length=254, verbose_name="구매자 이메일"
                    ),
                ),
                (
                    "pay_method",
                    models.CharField(
                        choices=[("card", "신용카드")],
                        default="card",
                        max_length=20,
                        verbose_name="결제수단",
                    ),
                ),
                (
                    "pay_status",
                    models.CharField(
                        choices=[
                            ("ready", "결제 준비"),
                            ("paid", "결제 완료"),
                            ("canceled", "결제 취소"),
                            ("failed", "결제 실패"),
                        ],
                        default="ready",
                        max_length=20,
                        verbose_name="결제상태",
                    ),
                ),
                (
                    "is_paid_ok",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name="결제성공 여부",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mall.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
